# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    # branches-ignore:
    #   - release
    # tags-ignore:
    #   - v*
  pull_request:
    # branches-ignore:
    #   - release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: node:16-bullseye
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Cache
        uses: actions/cache@v3
        id: cache-modules
        env:
          cache-name: cache-modules
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.OS }}-build-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('**/lockfiles') }}

      - name: npm build
        run: |
          openssl version
          node -v
          npm i
          npm run build --if-present
      - name: npm test
        run: |
          npm run test
        env:
          CI: true

