# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: manual-publish

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'major|minor|patch'
        required: true
        default: ''

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: node:16-bullseye
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node: [14]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Verify
        run: |
          echo $GITHUB_REF
          # echo ${{ github.ref }}
          export DEBIAN_FRONTEND=noninteractive
          apt-get -qq -y update > /dev/null
          apt-get -qq -y install dnsutils jq net-tools > /dev/null
          netstat -tunpl
          uname -a
          # github project/settings/Secrets/New repository secret: NPM_TOKEN
          npm whoami
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: npm build
        run: |
          openssl version
          node -v
          npm i -g standard-version
          npm i
          npm run build --if-present
      - name: npm ci
        run: |
          npm run test
        env:
          CI: true

      - name: npm publish
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          # git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          npm run release ${{ github.event.inputs.semver }}
          npm publish
          git push -v origin --follow-tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

